### ISSUE TITLE
Unable to install on Laravel 10

### ISSUE THREAD

**Issue by ElyGallego** [mstaack/laravel-postgis#185]
I tried to install the package in a new Laravel 10 project using the following command:

```
composer require "mstaack/laravel-postgis:6.*"
```

However, I encountered the following error message:

```
  Problem 1
    - bosnadev/database[0.21, ..., 0.21.1] require illuminate/database ^5.0|^6.0|^7.0|^8.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis 6.0 requires bosnadev/database ^0.21|master -> satisfiable by bosnadev/database[0.21, 0.21.1].
    - Root composer.json requires mstaack/laravel-postgis 6.* -> satisfiable by mstaack/laravel-postgis[6.0].
```

**Comment by mstaack** [comment]
can you try latest 6.1 version which i just published?

cheers max

**Comment by ElyGallego** [comment]
I did and I got a similar error message:
```
  Problem 1
    - bosnadev/database[0.21, ..., 0.21.1] require illuminate/database ^5.0|^6.0|^7.0|^8.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis 6.1 requires bosnadev/database ^0.21|dev-master -> satisfiable by bosnadev/database[0.21, 0.21.1].
    - Root composer.json requires mstaack/laravel-postgis 6.1 -> satisfiable by mstaack/laravel-postgis[6.1].
```

**Comment by krzysztofrewak** [comment]
@ElyGallego, @terehov-space, @mstaack, I opened PR here: https://github.com/bosnadev/database/pull/56

After merge and release it should work as expected.

**Comment by ElyGallego** [comment]
@krzysztofrewak Thanks, they already merged the PR, and I was able to install it on Laravel 10. Apparently they don't do new releases

**Comment by krzysztofrewak** [comment]
@ElyGallego, did you try it with `"minimum-stability": "stable"` in your `composer.json`? With `"dev"` works for me as well, but for stable it's still crashing.

**Comment by ElyGallego** [comment]
@krzysztofrewak Yeah, I have `"minimum-stability": "stable"` and it worked for me.
